export const SCHEDULE_CRON_METADATA = 'SCHEDULE_CRON_METADATA';
export const SCHEDULE_INTERVAL_METADATA = 'SCHEDULE_INTERVAL_METADATA';
export const SCHEDULE_TIMEOUT_METADATA = 'SCHEDULE_TIMEOUT_METADATA';
