export const MAX_PUBLIC_PROFILE_LINKS = 5;
export const MAX_PUBLIC_PROFILE_ABOUT_LENGTH = 512;
export const MAX_PUBLIC_PROFILE_LINK_LABEL_LENGTH = 64;
export const MAX_PUBLIC_PROFILE_LINK_ICON_LENGTH = 32;
export const MAX_PUBLIC_PROFILE_LINK_URL_LENGTH = 2048;
